import {
  acMiragePoster,
  alanWake,
  apexLegendsPoster,
  blackMyth,
  cyberPunkPoster,
  eldenRingPoster,
  farCryPoster,
  ghostOfTushimaPoster,
  godOfWarPoster,
  motalCombat,
  pesPoster,
  rdr2Poster,
  rE4Poster,
  spiderman,
  theLastOfUsPoster,
  theWitcher,
} from "../assets";

export const allGames = [
  {
    id: 1,
    name: "Cyberpunk 2077",
    date: "2020",
    review: "86",
    currentPrice: "30",
    genre: ["Action", "RPG"],
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X"],
    publisher: "CD Projekt",
    players: "single",
    online: false,
    image: cyberPunkPoster,
  },
  {
    id: 2,
    name: "Black Myth: Wukong",
    date: "2024",
    review: "93",
    originalPrice: "60",
    currentPrice: "51",
    discount: "15",
    genre: ["Action", "RPG"],
    platforms: ["PC", "PS5", "Xbox Series X"],
    publisher: "Game Science",
    players: "single",
    online: false,
    image: blackMyth,
  },
  {
    id: 3,
    name: "Elden Ring",
    date: "2022",
    review: "95",
    originalPrice: "60",
    currentPrice: "30",
    discount: "50",
    genre: ["Action", "RPG"],
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X"],
    publisher: "Bandai Namco",
    players: "single",
    online: true,
    image: eldenRingPoster,
  },
  {
    id: 4,
    name: "Assassin's Creed Mirage",
    date: "2023",
    review: "84",
    currentPrice: "30",
    genre: ["Action", "Adventure"],
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Xbox Series X"],
    publisher: "Ubisoft",
    players: "single",
    online: false,
    image: acMiragePoster,
  },
  {
    id: 5,
    name: "Resident Evil 4: Remake",
    date: "2023",
    review: "93",
    originalPrice: "60",
    currentPrice: "42",
    discount: "30",
    genre: ["Survival"],
    platforms: ["PC", "PS4", "PS5", "Xbox Series X"],
    publisher: "Capcom",
    players: "single",
    online: false,
    image: rE4Poster,
  },
  {
    id: 6,
    name: "Apex Legends",
    date: "2019",
    review: "88",
    genre: ["Battle", "Shooting"],
    platforms: [
      "PC",
      "PS4",
      "PS5",
      "Xbox One",
      "Xbox Series X",
      "Nintendo Switch",
    ],
    publisher: "Respawn Entertainment",
    players: "multiple",
    online: true,
    image: apexLegendsPoster,
  },
  {
    id: 7,
    name: "Far Cry 5",
    date: "2018",
    review: "78",
    currentPrice: "60",
    genre: ["Action", "Adventure"],
    platforms: ["PC", "PS4", "Xbox One"],
    publisher: "Ubisoft",
    players: "single",
    online: true,
    image: farCryPoster,
  },
  {
    id: 8,
    name: "PES 2021",
    date: "2020",
    review: "73",
    currentPrice: "45",
    genre: ["Sports"],
    platforms: ["PC", "PS4", "Xbox One"],
    publisher: "Konami",
    players: "multiple",
    online: true,
    image: pesPoster,
  },
  {
    id: 9,
    name: "Alan Wake 2",
    date: "2023",
    review: "93",
    originalPrice: "40",
    currentPrice: "32",
    discount: "20",
    genre: ["Adventure", "Survival"],
    platforms: ["PC", "PS5", "Xbox Series X"],
    publisher: "Remedy Entertainment",
    players: "single",
    online: false,
    image: alanWake,
  },
  {
    id: 10,
    name: "The Witcher 3: Wild Hunt",
    date: "2015",
    review: "93",
    originalPrice: "40",
    currentPrice: "32",
    discount: "20",
    genre: ["Action", "RPG"],
    platforms: ["PC", "PS4", "PS5", "Xbox One", "Nintendo Switch"],
    publisher: "CD Projekt",
    players: "single",
    online: false,
    image: theWitcher,
  },
  {
    id: 11,
    name: "Mortal Kombat 11",
    date: "2019",
    review: "72",
    currentPrice: "54",
    originalPrice: "62",
    discount: "20",
    genre: ["Action"],
    platforms: [
      "PC",
      "PS4",
      "PS5",
      "Xbox One",
      "Xbox Series X",
      "Nintendo Switch",
    ],
    publisher: "NetherRealm Studios",
    players: "multiple",
    online: true,
    image: motalCombat,
  },
  {
    id: 12,
    name: "Spider-Man 2",
    date: "2023",
    review: "87",
    originalPrice: "50",
    currentPrice: "35",
    discount: "30",
    genre: ["Action", "Adventure"],
    platforms: ["PS5"],
    publisher: "Insomniac Games",
    players: "single",
    online: false,
    image: spiderman,
  },
  {
    id: 13,
    name: "Red Dead Redemption II",
    date: "2018",
    review: "97",
    genre: ["Action", "Adventure"],
    platforms: ["PC", "PS4", "Xbox One"],
    publisher: "Rockstar Games",
    players: "single",
    online: true,
    image: rdr2Poster,
  },
  {
    id: 14,
    name: "The Last of Us Part II",
    date: "2020",
    review: "93",
    genre: ["Action", "Adventure"],
    platforms: ["PS4", "PS5"],
    publisher: "Naughty Dog",
    players: "single",
    online: false,
    image: theLastOfUsPoster,
  },
  {
    id: 15,
    name: "Ghost of Tsushima",
    date: "2020",
    review: "83",
    genre: ["Action", "Samurai"],
    platforms: ["PS4", "PS5"],
    publisher: "Sucker Punch Productions",
    players: "single",
    online: false,
    image: ghostOfTushimaPoster,
  },
  {
    id: 16,
    name: "God of War: Ragnarok",
    date: "2022",
    review: "94",
    genre: ["Action", "Adventure"],
    platforms: ["PS4", "PS5"],
    publisher: "Santa Monica Studio",
    players: "single",
    online: false,
    image: godOfWarPoster,
  },
];
