import {
  alanWake,
  blackMyth,
  motalCombat,
  spiderman,
  theWitcher,
} from "../assets";

export const allGames = [
  {
    id: 1,
    name: "Black Myth Wukong",
    date: "2024",
    review: "81",
    originalPrice: "60",
    currentPrice: "51",
    discount: "15",
    image: blackMyth,
  },
  {
    id: 2,
    name: "Alan Wake 2",
    date: "2024",
    review: "86",
    originalPrice: "40",
    currentPrice: "32",
    discount: "20",
    image: alanWake,
  },
  {
    id: 3,
    name: "Mortal Combat 11",
    date: "2023",
    review: "72",
    originalPrice: "62",
    currentPrice: "54",
    discount: "20",
    image: motalCombat,
  },
  {
    id: 4,
    name: "Spider-Man 2",
    date: "2023",
    review: "87",
    originalPrice: "50",
    currentPrice: "35",
    discount: "30",
    image: spiderman,
  },
  {
    id: 5,
    name: "The Witcher 3",
    date: "2015",
    review: "93",
    originalPrice: "40",
    currentPrice: "32",
    discount: "20",
    image: theWitcher,
  },
];
